// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghuswbuqjwujhrhnvqdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdodXN3YnVxand1amhyaG52cWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODAyNzgsImV4cCI6MjA2MDk1NjI3OH0.m8f7CZoP0AgCjNdRbE29WGTtd5xPGFxpfz5S3YQ_504";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);